"""Minimal type stub for the XPPython3 ``xp`` module.

Only the surface the plugin actually uses, typed so mypy can catch the real
hazard: ``findDataRef`` / ``findCommand`` return ``None`` when the ref/command
does not exist, and passing that ``None`` into ``getDataf``/``setDataf`` would
crash in-sim. With this stub, any un-guarded use is a type error.
"""

from collections.abc import Callable
from typing import Any

# Opaque handles (XPLMDataRef / XPLMCommandRef / hotkey / flight-loop ids).
DataRef = int
CommandRef = int

# --- datarefs / commands (the Optional-returning lookups) -------------------
def findDataRef(name: str) -> DataRef | None: ...
def findCommand(name: str) -> CommandRef | None: ...
def getDataf(ref: DataRef) -> float: ...
def getDatai(ref: DataRef) -> int: ...
def setDataf(ref: DataRef, value: float) -> None: ...
def setDatai(ref: DataRef, value: int) -> None: ...
def commandOnce(cmd: CommandRef) -> None: ...

# --- hotkeys ----------------------------------------------------------------
def registerHotKey(
    key: int, flags: int, description: str, callback: Callable[..., Any], refCon: Any = ...
) -> int: ...
def unregisterHotKey(hotKeyID: int) -> None: ...

# --- flight loops -----------------------------------------------------------
def createFlightLoop(callback: Callable[..., Any], phase: int = ..., refCon: Any = ...) -> int: ...
def scheduleFlightLoop(loopID: int, interval: float, relativeToNow: int = ...) -> None: ...
def destroyFlightLoop(loopID: int) -> None: ...

# --- misc -------------------------------------------------------------------
def speakString(text: str) -> None: ...
def log(message: str) -> None: ...

# Virtual-key + modifier-flag constants used for the push-to-talk hotkey.
VK_Z: int
DownFlag: int
UpFlag: int
ControlFlag: int
